<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CoursePage.aspx.cs" Inherits="Comp229_Assign03.CoursePage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <h2>Course</h2>
    <img src="img/Course.png" />


                 <div class="row">
        <div class="col-md-12">
            <div class="Default_List">
                <h4>Add Student</h4><br />
             <b> First Name: </b><asp:TextBox ID="txtFname1" CssClass="form-control" runat="server"></asp:TextBox>
           <b>Last Name: </b><asp:TextBox ID="txtLname1" CssClass="form-control" runat="server"></asp:TextBox>
                
                <asp:Button ID="RegisterStudentToCourse"  class="btn dropdown-toggle" runat="server" Text="Register" OnClick="RegisterStudentToCourse_Click" />
            <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>    
            </div>
                      <div class="Default_List">
                          
            <h4>Student List</h4>
               <asp:GridView ID="CourseGridView" class="table table-hover" Width="50%" runat="server" horizontalalign="Center" AutoGenerateColumns="False" DataKeyNames="StudentID" AutoGenerateDeleteButton="True" OnSelectedIndexChanged="CourseGridView_SelectedIndexChanged" >
                  <Columns>
                      <asp:BoundField DataField="StudentID" HeaderText="StudentID" InsertVisible="False" ReadOnly="True" SortExpression="StudentID" />
                      <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                      <asp:BoundField DataField="FirstMidName" HeaderText="FirstMidName" SortExpression="FirstMidName" />
<%--                      <asp:BoundField DataField="CourseID" HeaderText="CourseID" SortExpression="CourseID" />--%>
<%--                      <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />--%>

                  </Columns>
              </asp:GridView>
            
              <asp:GridView ID="CourseGridView1" runat="server" horizontalalign="Center" AutoGenerateColumns="False" DataKeyNames="StudentID" AutoGenerateDeleteButton="True" OnSelectedIndexChanged="CourseGridView_SelectedIndexChanged" DataSourceID="CourseDataSource">
                  <Columns>
                      <asp:BoundField DataField="StudentID" HeaderText="StudentID" InsertVisible="False" ReadOnly="True" SortExpression="StudentID" />
                      <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                      <asp:BoundField DataField="FirstMidName" HeaderText="FirstMidName" SortExpression="FirstMidName" />
<%--                      <asp:BoundField DataField="CourseID" HeaderText="CourseID" SortExpression="CourseID" />--%>
<%--                      <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />--%>

                  </Columns>
              </asp:GridView>

           

           
              <asp:SqlDataSource ID="CourseDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:Comp229Assign03 %>" 
                  SelectCommand="SELECT s.StudentID, s.LastName, s.FirstMidName FROM Students s"
                  deletecommand="Delete from Enrollments Where EnrollmentID = @EnrollmentID">
                  <SelectParameters>

                  </SelectParameters>
                  <DeleteParameters>
        <asp:Parameter Name="EnrollmentID" />
                      </DeleteParameters>
                       

              </asp:SqlDataSource>
            
              </div>
            </div>
         
           <h3>Register Student</h3>
            
            First Name: <asp:TextBox CssClass="form-control" ID="txtfName" runat="server" Width="170px" Wrap="False"></asp:TextBox><br />
        Last Name: <asp:TextBox CssClass="form-control" Width="170px" ID="txtlName" runat="server"></asp:TextBox><br />
         Course: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<asp:TextBox CssClass="form-control" Width="170px" ID="txtCourse" runat="server"></asp:TextBox><br />
            <div style="margin-top:30px;">
                 <asp:Button class="btn dropdown-toggle" ID="btnWrite" runat="server" Text="Register" 
                Onclick="btnWrite_Click"/>&nbsp;


        
                </div>
          <%--   StudentID:
            <asp:Label ID="lblID" runat="server" Text="StudentID"></asp:Label><br />
            FirstName:
            <asp:Label ID="lblFname" runat="server" Text="FirstName"></asp:Label><br />
                LastName:   
              <asp:Label ID="lblLname" runat="server" Text="LastName"></asp:Label><br />

              CourseID:
          <asp:Label ID="lblCid" runat="server" Text="CourseID"></asp:Label><br />
            Title:
            <asp:Label ID="lblTitle" runat="server" Text="Title"></asp:Label><br />
            
           --%> 
              

    </div>
</asp:Content>
