<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CoursePage.aspx.cs" Inherits="Comp229_Assign03.CoursePage" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <h2>Course</h2>
    <img src="img/Course.png" />


    <div class="row">
        <div class="col-md-12">
            <div class="Default_List">

                <%--Adding New Student Data to Selected Course--%>

                <h4>Add Student</h4>

                <b>First Name: </b>
                <asp:TextBox CssClass="form-control" ID="txtfName" runat="server" Width="170px" Wrap="False"></asp:TextBox>
                <b>Last Name: </b>
                <asp:TextBox CssClass="form-control" Width="170px" ID="txtlName" runat="server"></asp:TextBox>
                <b>Course:</b> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<asp:TextBox CssClass="form-control" Width="170px" ID="txtCourse" runat="server"></asp:TextBox>
                <div style="margin-top: 30px;">
                    <asp:Button class="btn dropdown-toggle" ID="btnWrite" runat="server" Text="Register"
                        OnClick="btnWrite_Click" />&nbsp;

                </div>
            </div>
            <div class="Default_List">

                <%-- First List of Student for Selected Course (Using procedure)
                   It's working only to show list. It doesn't work for deleting properly --%>
                <h4>Student List</h4>
                <b>To Show Student List of this Course</b><br />
                
                <asp:GridView ID="CourseGridView" class="table table-hover" Width="50%" runat="server" HorizontalAlign="Center" AutoGenerateColumns="False" DataKeyNames="StudentID" OnSelectedIndexChanged="CourseGridView_SelectedIndexChanged">
                    <Columns>
                        <asp:BoundField DataField="StudentID" HeaderText="StudentID" InsertVisible="False" ReadOnly="True" SortExpression="StudentID" />
                        <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                        <asp:BoundField DataField="FirstMidName" HeaderText="FirstMidName" SortExpression="FirstMidName" />
                    </Columns>
                </asp:GridView>

                <%-- Second List of Student for Selected Course (Using datasource)
                    It's working only to delete list. It doesn't work properly for displaying list 
                    So please use this table to delete--%>

                <b>To delete specific student from this course</b><br />
                <asp:GridView ID="CourseGridView1" runat="server" HorizontalAlign="Center" AutoGenerateColumns="False" DataKeyNames="StudentID" AutoGenerateDeleteButton="True" OnSelectedIndexChanged="CourseGridView_SelectedIndexChanged" DataSourceID="CourseDataSource">
                    <Columns>
                        <asp:BoundField DataField="StudentID" HeaderText="StudentID" InsertVisible="False" ReadOnly="True" SortExpression="StudentID" />
                        <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                        <asp:BoundField DataField="FirstMidName" HeaderText="FirstMidName" SortExpression="FirstMidName" />
                    </Columns>
                </asp:GridView>

                <%--DataSource for Second List--%>

                <asp:SqlDataSource ID="CourseDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:Comp229Assign03 %>"
                    SelectCommand="SELECT [StudentID], [LastName], [FirstMidName] FROM [Students]"
                    DeleteCommand="Delete from Enrollments Where EnrollmentID = @EnrollmentID">
                    <SelectParameters>
                        <asp:Parameter Name="CourseID" />
                    </SelectParameters>
                    <DeleteParameters>
                        <asp:Parameter Name="EnrollmentID" />
                    </DeleteParameters>


                </asp:SqlDataSource>

            </div>


        </div>
    </div>
</asp:Content>
