<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="WebForm4.aspx.cs" Inherits="Comp229_Assign03.WebForm4" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <h3>Course</h3>
    <img src="img/Course.png" />
    <div class="Default_List">
        
          <div class="Default_List">
          <%--   StudentID:
            <asp:Label ID="lblID" runat="server" Text="StudentID"></asp:Label><br />
            FirstName:
            <asp:Label ID="lblFname" runat="server" Text="FirstName"></asp:Label><br />
                LastName:   
              <asp:Label ID="lblLname" runat="server" Text="LastName"></asp:Label><br />

              CourseID:
          <asp:Label ID="lblCid" runat="server" Text="CourseID"></asp:Label><br />
            Title:
            <asp:Label ID="lblTitle" runat="server" Text="Title"></asp:Label><br />
            
           --%> 
              <asp:GridView ID="CourseGridView" runat="server" horizontalalign="Center" AutoGenerateColumns="False" DataKeyNames="StudentID" AutoGenerateDeleteButton="True">
                  <Columns>
                      <asp:BoundField DataField="StudentID" HeaderText="StudentID" InsertVisible="False" ReadOnly="True" SortExpression="StudentID" />
                      <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                      <asp:BoundField DataField="FirstMidName" HeaderText="FirstMidName" SortExpression="FirstMidName" />
                      <asp:BoundField DataField="CourseID" HeaderText="CourseID" SortExpression="CourseID" />
                      <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />

                  </Columns>
              </asp:GridView>
            
           
              </div>
          <div class="Default_List">
            <h3>Register Student</h3>
            
            First Name: <asp:TextBox ID="txtfName" runat="server"></asp:TextBox><br />
        Last Name: <asp:TextBox ID="txtlName" runat="server"></asp:TextBox><br />
            <asp:Button ID="btnWrite" runat="server" Text="Register" 
                Onclick="btnWrite_Click"/>
            <asp:Label ID="label2" runat="server"></asp:Label>
  </div>


    </div>
</asp:Content>
